name: scancodeio
services:
  db:
    image: docker.io/library/postgres:13
    env_file:
      - docker.env
    volumes:
      - db_data:/var/lib/postgresql/data/
    shm_size: "1gb"
    restart: always

  redis:
    image: docker.io/library/redis
    # Enable redis data persistence using the "Append Only File" with the
    # default policy of fsync every second. See https://redis.io/topics/persistence
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: always

  web:
    build:
      context: .
      args:
        HOST_UID: 1000
        HOST_GID: 1000
    command: wait-for-it --strict --timeout=60 db:5432 -- sh -c "
        if [ ! -w /opt/scancodeio/static_files ]; then
            mkdir -p /opt/scancodeio/static_files
            echo 'Created static_files directory'
        fi &&
        ./manage.py migrate &&
        ./manage.py collectstatic --no-input --verbosity 0 --clear &&
        gunicorn scancodeio.wsgi:application --bind :8000 --timeout 600 --workers 8 ${GUNICORN_RELOAD_FLAG:-}"
    env_file:
      - docker.env
    ports:
      - "8001:8000"  # Expose web container port to host on 8001
    volumes:
      - .env:/opt/scancodeio/.env
      - /etc/scancodeio/:/etc/scancodeio/
      - workspace:/var/scancodeio/workspace/
      - ./static:/opt/scancodeio/static_files
    depends_on:
      - db
    restart: always

  worker:
    build:
      context: .
      args:
        HOST_UID: 1000
        HOST_GID: 1000
    # Ensure that potential db migrations run first by waiting until "web" is up
    command: wait-for-it --strict --timeout=120 web:8000 -- sh -c "
        ./manage.py rqworker --worker-class scancodeio.worker.ScanCodeIOWorker
                             --queue-class scancodeio.worker.ScanCodeIOQueue
                             --verbosity 1"
    env_file:
      - docker.env
    volumes:
      - .env:/opt/scancodeio/.env
      - /etc/scancodeio/:/etc/scancodeio/
      - workspace:/var/scancodeio/workspace/
    depends_on:
      - redis
      - db
      - web
    restart: always
    
  # Removing the nginx container as we're using the system's nginx service
  # We're exposing the web container directly to be accessed by the host's nginx

  clamav:
    image: docker.io/clamav/clamav
    volumes:
      - clamav_data:/var/lib/clamav
      - workspace:/var/scancodeio/workspace/
    restart: always

volumes:
  db_data:
  redis_data:
  clamav_data:
  workspace:
